version: '3.8'

services:
  backend:
    build:
      context: ./Servidor
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./Servidor:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  frontend:
    build:
      context: ./Tiendaa
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./Tiendaa:/app
      - /app/node_modules
